import { NextResponse } from 'next/server';
import type { PublicPlanConfig, WaCountryRate } from '@/types/pricing';

const PLANS: PublicPlanConfig[] = [
  {
    tier: 'SEMILLA',
    n: 'Plan Semilla',
    tl: 'Para iglesias que comienzan',
    color: '#1DC98C',
    price: 49,
    maxM: 150,
    maxV: 40,
    maxS: 1,
    waI: 0,
    waO: 0,
    ag12: false,
    ag: [2, 4, 5],
    bespoke: false,
    network: false,
    cta: 'Comenzar gratis →',
    ctaHref: '/schedule?plan=semilla',
  },
  {
    tier: 'COSECHA',
    n: 'Plan Cosecha',
    tl: 'Para iglesias en crecimiento activo',
    color: '#F0B83C',
    price: 149,
    maxM: 500,
    maxV: 150,
    maxS: 2,
    waI: 800,
    waO: 2.50,
    ag12: true,
    ag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bespoke: false,
    network: false,
    cta: 'Más popular →',
    ctaHref: '/schedule?plan=cosecha',
  },
  {
    tier: 'REINO',
    n: 'Plan Reino',
    tl: 'Para iglesias grandes',
    color: '#26D9D9',
    price: 299,
    maxM: 1500,
    maxV: 400,
    maxS: 4,
    waI: 2500,
    waO: 2.00,
    ag12: true,
    ag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bespoke: false,
    network: false,
    cta: 'Solicitar demo →',
    ctaHref: '/schedule?plan=reino',
  },
  {
    tier: 'GLORIA',
    n: 'Plan Gloria',
    tl: 'Para megaiglesias y campuses múltiples',
    color: '#E84855',
    price: 0,
    maxM: 99999,
    maxV: 9999,
    maxS: 9,
    waI: 0,
    waO: 1.50,
    ag12: true,
    ag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bespoke: true,
    network: false,
    cta: 'Solicitar cotización →',
    ctaHref: '/contact?plan=gloria',
  },
  {
    tier: 'RED',
    n: 'Plan Red',
    tl: 'Para redes y denominaciones',
    color: '#9B8FFF',
    price: 94.90,
    maxM: 99999,
    maxV: 9999,
    maxS: 9,
    waI: 1200,
    waO: 1.75,
    ag12: true,
    ag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bespoke: false,
    network: true,
    cta: 'Contactar →',
    ctaHref: '/contact?plan=red',
  },
];

const WA_RATES: WaCountryRate[] = [
  { countryCode: 'CO', ratePerConv: 0.0147 },
  { countryCode: 'MX', ratePerConv: 0.0169 },
  { countryCode: 'PE', ratePerConv: 0.0151 },
  { countryCode: 'CL', ratePerConv: 0.0138 },
  { countryCode: 'AR', ratePerConv: 0.0122 },
  { countryCode: 'VE', ratePerConv: 0.0147 },
  { countryCode: 'EC', ratePerConv: 0.0155 },
  { countryCode: 'BO', ratePerConv: 0.0149 },
  { countryCode: 'GT', ratePerConv: 0.0143 },
  { countryCode: 'DO', ratePerConv: 0.0152 },
  { countryCode: 'OTHER', ratePerConv: 0.015 },
];

export async function GET() {
  return NextResponse.json(
    { plans: PLANS, rates: WA_RATES },
    {
      headers: {
        'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
      },
    }
  );
}
